DROP TABLE IF EXISTS novels;

-- Create the Table Structure
CREATE TABLE IF NOT EXISTS novels
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    author character varying(255),
    cover_url character varying(255),
    description character varying(1000),
    details character varying(255),
    featured boolean,
    price double precision,
    published_year integer,
    title character varying(255),
    CONSTRAINT novels_pkey PRIMARY KEY (id)
    );